### ISSUE TITLE
Testing: CSV Import compatibility

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Mapping#111]
The `fix-mappings-api` branch should fix the errors that occurred when using the CSV Import module to update items with markers. It will need testing to confirm.

**Comment by jimsafley** [comment]
It' also important to do a quick check whether the Mapping feature works as expected on the item add/edit pages.

**Comment by allanaaa** [comment]
Looks good to me, no errors popping up anymore. Items looks fine. 

Only one thing:
The "Map Browse" page doesn't seem to be showing the selected basemap. The page block works fine for that. 

I wonder if basemaps could have a site setting as well, so that item maps can also have a basemap set across the whole site? Would that be complicated to implement?

**Comment by jimsafley** [comment]
Some basemap providers are inconsistently available, for whatever reason. In the event it's not available, it always falls back to the default basemap. I'd wager that not all basemaps are unavailable.

**Comment by zerocrates** [comment]
The problem there is not that the basemap isn't available, but that there's no way to configure one for the map browse, right? Like, that setting exists only for the block. The page one exists just in the navigation, I guess, actually.

Edit sorry, that's unclear: I mean to say that the basemap setting for map browse works through the navigation only and uses a GET param: so if you go straight to map/browse, it will never apply the setting. Not sure if that's what you're seeing.

The point about applying it to item shows is maybe more significant.
