### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Mapping#20]
@jannellelegg @mebrett

This module needs testing. Download and install the module and make sure you already have a few items, each with a few media. Confirm the following is true:
- When adding or editing an item there's a "Mapping" tab that contains a map interface
- The map interface contains the following controls (confirm that each works):
  - "Zoom in" (zooms the map in)
  - "Zoom out" (zooms the map out)
  - "Draw a marker" (gives the ability to add a marker)
  - "Edit layers" (gives the ability to move markers)
  - "Delete layers" (gives the ability to delete markers)
  - "Enter address" (gives the ability to geocode an address)
  - "Set the current view as the default center and zoom level"
  - "Go to current default view" (pans and zooms map to default view, set above)
  - "Clear the default center and zoom level" (pans and zooms to the initial view)
  - switch layers control (top-right) with "Streets", "Grayscale", "Satellite", and "Terrain" options
- Clicking on a marker opens a popup where you can:
  - enter the marker's label
  - select the marker's image (confirm that image selection works; item must already have image media)
- After saving the item, the item show page will have a "Mapping" tab that contains a map
- The map will:
  - be set to the center/zoom level you set above
  - contain the marker(s) you saved
  - when clicking a marker, a popup will open with the label and image you set above
- The map contains the following controls (confirm that each works):
  - "Zoom in" (zooms the map in)
  - "Zoom out" (zooms the map out)
  - "Fit all markers on the map within one view"
  - switch layers control (top-right) with "Streets", "Grayscale", "Satellite", and "Terrain" options

If anything is _not_ true, if you notice a bug, or if you need further clarification, contact me via Slack or this issue. There's more to test, but let's start with this.

**Comment by mebrett** [comment]
Everything is functional.
A few notes: 
- A (positive) note on the map view on the item show page - it auto-zooms for pins if you haven't saved a default zoom. This is very helpful!
- Is there any way to get the overall default zoom level a little less out? As it is, I get to see North America twice over and ton of Antarctica. (Might be useful as a Global Admin option, at least). It gets a bit frustrating because either you start by doing a lot of panning and zooming, or you search and the module drops a pin which you then have to delete (a not entirely intuitive process)

**Comment by jannellelegg** [comment]
No issues with the map controls, creating/editing markers and labels, modifying the view, or viewing a map on the item page.
- I didn't have the problem with default zoom that Megan described above until I made my browser window larger. 
- I did notice that the maps are not generating on the front end yet (we're not testing for it yet, but in case you needed additional info- the map frame generated, but layers did not appear. So it's just a grey box right now.)

**Comment by jimsafley** [comment]
@jannellelegg @mebrett

Thanks for your input. Let's move on to testing maps in sites. Confirm the following is true:
- When adding or editing a site page there's a "Map" option in the "Add New Block" sidebar
- Clicking the "Map" option adds a  "Map" block to the form containing the following expandable/collapsible sections:
  - "Default View"
  - "WMS Overlays"
  - "Attachments"
- The "Default View" section contains a map interface that contains the following controls (confirm that each works)
  - "Zoom in" (zooms the map in)
  - "Zoom out" (zooms the map out)
  - "Set the current view as the default center and zoom level"
  - "Go to current default view" (pans and zooms map to default view, set above)
  - "Clear the default center and zoom level" (pans and zooms to the initial view)
- The "WMS Overlays" section contains a form with the following elements (*):
  - A list of WMS overlays (once added) with the following features:
    - Set default overlay checkbox (sets an overlay on by default; only one can be checked at a time)
    - Edit icon (populates below inputs with overlay data)
    - Delete icon (deletes this overlay)
  - "Label" input (required)
  - "Base URL" input (required)
  - "Layers" input
  - "Styles" input
  - "Add Overlay" button (add only; adds a new overlay to list)
  - "Save Changes" button (edit only; saves changes to an existing overlay)
  - "Clear Inputs" button (clears above inputs)
- You can add items (preferably ones that have markers) to the block via the "Attachments" section

**Evaluate the public map block by saving all your changes and clicking the "View" button.**

(*) I've been using [Map Warper](http://mapwarper.net/) to test the WMS overlay feature. Every map on that site has an "Export" option where you can copy the "WMS Capabilities URL" and enter it into the "Base URL" input. Try to find several different maps that occupy the same geographic space and add them to the map.

**Comment by jannellelegg** [comment]
Everything worked great for me. [Is there anything I should have put in the "Layers" or "Styles" fields? I left them blank.

I also confirmed that on the public map block, the icons populated and when clicked, populated info/images. The layer toggle was also functional and I was able to change between maps from the public side.

One thing I noticed- the Default viewer map is smaller than the map displayed on the public page, so when you set the current view as the default center and zoom level, it is not as precisely centered/zoomed as you might think when setting it.

**Comment by jimsafley** [comment]
I changed the way we set default views. There is little visual change to the interface, but the results should be more expected (see 1531cc1d9392cec1d94c716b38a59fc2793e1eb5). Pull from master and try it out. **Note that you must first uninstall and reinstall the module.**

**Comment by mebrett** [comment]
Uninstalled, pulled, installed. Maps for pages still works. BUT:
<img width="1273" alt="screen shot 2016-06-15 at 11 33 04 am" src="https://cloud.githubusercontent.com/assets/2314070/16086461/9de5ef0c-32ed-11e6-89e2-98609f2d6067.png">

The latest update has done something to the item/edit view so that it's a blank screen.

**Comment by jimsafley** [comment]
The most recent commit should fix it. To be sure, pull the most recent changes to omeka-s as well.

**Comment by mebrett** [comment]
That fixed it!

**Comment by jannellelegg** [comment]
The recent update did improve the relationship between the default view and the front end view (in terms of setting the scale of the map).

However, the points are no longer being plotted in the default viewer or front-end. 
I attempted to remove an item and re-add it, and noted that "Add Attachment" is no longer populating items for selection. (For comparison, adding an item to the Item Showcase block loads 20 options)
![nopoints-noattachment](https://cloud.githubusercontent.com/assets/5897725/16087069/b23eba0e-32ef-11e6-995b-ede5cb597375.png)
![attachment](https://cloud.githubusercontent.com/assets/5897725/16087071/b6e1d46a-32ef-11e6-8985-beefd89baa43.png)

**Comment by jimsafley** [comment]
@jannellelegg do any of your items have markers? The attachment sidebar only lists items that have markers.

**Comment by jannellelegg** [comment]
When adding/editing a map in the edit item screen, the option to save changes to the marker is not clear. The only visible option is to click "save" at the top of the page - which doesn't preserve the changes to the marker label.

![screen shot 2016-06-15 at 12 11 29 pm](https://cloud.githubusercontent.com/assets/5897725/16087901/c5724fa2-32f2-11e6-9bdd-b209e86fd252.png)

If a user clicks the marker to edit the label (rather than selecting the edit an item button) the Edit an Item button doesn't highlight or indicate that it is being utilized, or that you should save the changes by pressing save.

![screen shot 2016-06-15 at 12 11 45 pm](https://cloud.githubusercontent.com/assets/5897725/16087970/0001e146-32f3-11e6-9f09-e3930d5f8823.png)

On the other hand, the Delete Layers function is only possible if you click the button, which reveals the save/cancel dialog.

**Comment by jannellelegg** [comment]
Jim, good question - it looks like the last update deleted the maps for those items. I've re-added the map to the items and that fixed it. Thanks - I should have double-checked the items!

**Comment by jimsafley** [comment]
@jannellelegg The "Edit Layers" in-map control is confusing. Instead, it should say "Move markers" since its only function is to allow users to click and drag markers. The actual editing of a marker happens in the popup. Would changing the label to "Move markers" help matters?

This reminds me: per #18 I need someone to write (clear and concise) instructions for using the map interface. Would you mind taking a stab at it?

**Comment by jimsafley** [comment]
@jannellelegg I modified the toolbar button labels to better reflect what they do (see aa3848b01d3a0bc7981ef78325ad97f14a991e52). Hopefully this improves the user experience.

**Comment by jannellelegg** [comment]
The change to "Move Markers" works for me. Is hitting "Save" at the top of the page meant to save the changes to the text in the pop-up window? If so, it's not always sticking? I'll keep trying to reproduce the problem and see if I can figure out how/why it might be happening based on what I'm doing.

Sure, I'm happy to work on some instructions.

**Comment by jimsafley** [comment]
Yes, something's wrong if the marker label isn't being saved after clicking "Save".

**Comment by jimsafley** [comment]
@jannellelegg @mebrett 

Where do you stand on testing this module? Other than existing issues, have you discovered any bugs or unexpected behavior? Do you have ideas for improvement? I remember that you've drafted documentation. Where is that? From your perspective, is this plugin ready to be released to the public?

**Comment by mebrett** [comment]
Documentation is here: https://github.com/omeka/omeka-s-enduser/blob/master/modules/mapping.md

**Comment by mebrett** [comment]
The new default view is great, everything is working fine and I think we're ready for a public release.

Not to hold up the release, but for future discussion (and perhaps public input): I do still wish there was a way to set the default zoom level when adding markers to an item. I understand that different sites within a single install may be working with different areas. However, setting a default zoom level (with a center) means that when someone searches for a different area, they're still zoomed in to that point. Rather than seeing the whole world and either having to zoom in multiple times (7-10 clicks, depending on how close to exact you're trying to be)\* to get even close to seeing the exact location where your marker is going, you could search for a location and just have the map reorient.  (*the zoom isn't so bad when I have a mouse, because I can scroll to zoom in, but testing sans mouse on Wednesday I got very tired of clicking 10 times to zoom in every time I worked with a new item).

**Comment by jimsafley** [comment]
Why doesn't the "Set the current view as the default view" work here?

**Comment by mebrett** [comment]
Because it only applies per item. I was thinking about an install-level default zoom.

**Comment by alyssafahringer** [comment]
Tested in Chrome, Safari, Firefox - didn't find any bugs.
