### ISSUE TITLE
Timeline across the full width of the main div, below map

### ISSUE THREAD

**Issue by sharonmleon** [omeka-s-modules/Mapping#54]
Can we build out this front end configuration so that the timeline extends across the full bottom of the main div? That would leave the upper portiton of the display evenly split between the item pane and the map pane.

**Comment by jimsafley** [comment]
@kimisgold The timeline nav consists of the `tl-timenav` and `tl-menubar` divs. Can you visually move these under the map? (We can control the position of the timeline nav using the `timenav_position` configuration, but this only controls whether it's immediately above or under the slide div.)

**Comment by kimisgold** [comment]
Yes, I can. If you provide a branch with the desired configuration setup, I'll draft the styles there.

**Comment by jimsafley** [comment]
The master branch already has the desired configuration setup.

**Comment by jimsafley** [comment]
@kimisgold In 98ab56af387c3718ca24110b9e04ca44d3586900 I changed `.full-width` to `.timenav-full-width-below`. This is an attempt to allow for additional timenav positions, should we want them. For example, a hypothetical `.timenav-full-width-above` would indicate that the timeline navigation goes the full width above the story slider and map. Do you think this is a good approach to naming the class? If so, if it's not too much trouble, I think we should go ahead and implement `.timenav-full-width-above` since the configuration is already primed for it.

**Comment by jimsafley** [comment]
Feature added in cfef141a8caaebaec4bbf49fa977bd66cac93c78
